baseURL = "https://cchirag.github.io/loggg"
languageCode = "en-us"
title = "loggg"
theme = "PaperMod"

[params]
  author = "Chirag Chandrashekhar"
  ShowReadingTime = true
  ShowBreadCrumbs = true
[params.profileMode]
enabled = true
title = "Hi there ðŸ‘‹"
subtitle = "This is a collection of posts and notes from my development work. Iâ€™m currently working on mint, a single-file key-value store written in Go."

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/loggg/posts"

[[params.profileMode.buttons]]
  name = "Mint"
  url = "https://github.com/cchirag/mint"

[[params.socialIcons]]
name = "github"
url = "https://github.com/cchirag"

[[params.socialIcons]]
name = "x"
url = "https://x.com/chiragchan"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = 'G-HCE4FJHL73'
